global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf-1:9273", "telegraf-2:9274"]
  - job_name: "python-exporter-plus"
    static_configs:
      - targets: ["python-exporter-plus:8000"]